"""
DataSentinel V&V — PDF Report Generator
Produces a professional verification report for carbon registry submission.
Uses reportlab (Platypus) for structured multi-page output.
"""
import io
from datetime import datetime
from typing import Dict, List

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    HRFlowable,
    KeepTogether,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

# ── Brand colours ───────────────────────────────────────────────────────────
CANYON   = colors.HexColor('#D4621A')
OLIVINE  = colors.HexColor('#7A8C2E')
AMBER    = colors.HexColor('#C9A227')
RED_FAIL = colors.HexColor('#C0392B')
SURFACE  = colors.HexColor('#F5F3EF')
SURFACE2 = colors.HexColor('#EAE7E2')
BORDER   = colors.HexColor('#D5D0C8')
DARK     = colors.HexColor('#1A1816')
MID      = colors.HexColor('#4A4440')
MUTED    = colors.HexColor('#8A8480')
WHITE    = colors.white

PAGE_W, PAGE_H = A4
MARGIN = 18 * mm


def _styles():
    base = getSampleStyleSheet()
    def S(name, **kw):
        s = ParagraphStyle(name, parent=base['Normal'], **kw)
        return s

    return {
        'title':     S('ds_title',    fontName='Helvetica-Bold',   fontSize=22, textColor=DARK,   spaceAfter=4,  leading=26),
        'subtitle':  S('ds_sub',      fontName='Helvetica',         fontSize=11, textColor=MID,    spaceAfter=2),
        'h1':        S('ds_h1',       fontName='Helvetica-Bold',   fontSize=13, textColor=DARK,   spaceBefore=14, spaceAfter=6, leading=16),
        'h2':        S('ds_h2',       fontName='Helvetica-Bold',   fontSize=10, textColor=CANYON, spaceBefore=10, spaceAfter=4, leading=12, textTransform='uppercase'),
        'body':      S('ds_body',     fontName='Helvetica',         fontSize=9,  textColor=MID,    spaceAfter=4,  leading=13, alignment=TA_JUSTIFY),
        'body_sm':   S('ds_body_sm',  fontName='Helvetica',         fontSize=8,  textColor=MUTED,  spaceAfter=3,  leading=11),
        'bold':      S('ds_bold',     fontName='Helvetica-Bold',   fontSize=9,  textColor=DARK,   spaceAfter=4,  leading=13),
        'mono':      S('ds_mono',     fontName='Courier',           fontSize=8,  textColor=MID,    spaceAfter=2,  leading=11),
        'centre':    S('ds_centre',   fontName='Helvetica',         fontSize=9,  textColor=MID,    alignment=TA_CENTER),
        'label':     S('ds_label',    fontName='Helvetica-Bold',   fontSize=7,  textColor=MUTED,  spaceAfter=1,  leading=9, textTransform='uppercase'),
        'finding_ok':S('ds_fok',      fontName='Helvetica',         fontSize=8,  textColor=MID,    leading=11, spaceAfter=2),
        'cp_id':     S('ds_cpid',     fontName='Courier-Bold',      fontSize=7.5,textColor=CANYON, leading=10),
    }


def _outcome_color(outcome: str):
    return {
        'verified':     OLIVINE,
        'conditional':  AMBER,
        'not_verified': RED_FAIL,
    }.get(outcome, MUTED)


def _outcome_label(outcome: str):
    return {
        'verified':     'VERIFIED',
        'conditional':  'CONDITIONAL',
        'not_verified': 'NOT VERIFIED',
    }.get(outcome, outcome.upper().replace('_', ' '))


def _status_color(status: str):
    return {
        'passed':  OLIVINE,
        'failed':  RED_FAIL,
        'warning': AMBER,
    }.get(status, MUTED)


def _header_footer(canvas, doc):
    """Draws header/footer on every page."""
    canvas.saveState()
    w, h = A4

    # Top bar
    canvas.setFillColor(DARK)
    canvas.rect(0, h - 10*mm, w, 10*mm, fill=1, stroke=0)
    canvas.setFillColor(WHITE)
    canvas.setFont('Helvetica-Bold', 8)
    canvas.drawString(MARGIN, h - 6.5*mm, 'DataSentinel')
    canvas.setFont('Helvetica', 7)
    canvas.drawString(MARGIN + 52, h - 6.5*mm, '·  V&V Verification Report')
    canvas.setFont('Helvetica', 7)
    canvas.drawRightString(w - MARGIN, h - 6.5*mm, f'CONFIDENTIAL  ·  Page {doc.page}')

    # Bottom bar
    canvas.setFillColor(SURFACE2)
    canvas.rect(0, 0, w, 8*mm, fill=1, stroke=0)
    canvas.setFillColor(MUTED)
    canvas.setFont('Helvetica', 6.5)
    canvas.drawString(MARGIN, 2.8*mm, 'Generated by DataSentinel V&V Platform  ·  Third-party verification for carbon registries')
    canvas.drawRightString(w - MARGIN, 2.8*mm, datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC'))

    # Accent line below header
    canvas.setStrokeColor(CANYON)
    canvas.setLineWidth(1.5)
    canvas.line(0, h - 10*mm, w, h - 10*mm)

    canvas.restoreState()


def generate_vv_pdf(project: Dict, report: Dict, checkpoints: List[Dict], documents: List[Dict]) -> bytes:
    """
    Generate a professional V&V verification report PDF.
    Returns bytes of the PDF.
    """
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=MARGIN, rightMargin=MARGIN,
        topMargin=18*mm, bottomMargin=14*mm,
        title=f"Verification Report — {project.get('name','Project')}",
        author='DataSentinel V&V Platform',
        subject='Carbon Registry Verification Report',
    )

    S = _styles()
    story = []

    outcome = report.get('overall_outcome', 'conditional')
    outcome_color = _outcome_color(outcome)
    outcome_label = _outcome_label(outcome)
    stats = report.get('report_data', {})
    registry_slug = project.get('registry_slug', 'puro_earth').replace('_', '.').title()
    methodology = project.get('methodology_code', '')
    generated_at = report.get('generated_at', datetime.utcnow().isoformat())
    try:
        gen_dt = datetime.fromisoformat(generated_at.replace('Z',''))
        gen_str = gen_dt.strftime('%d %B %Y, %H:%M UTC')
    except Exception:
        gen_str = generated_at

    # ── COVER BLOCK ─────────────────────────────────────────────────────────
    # Outcome badge table
    badge_color = outcome_color
    badge_data = [[
        Paragraph(f'<font color="#FFFFFF"><b>{outcome_label}</b></font>', ParagraphStyle(
            'badge', fontName='Helvetica-Bold', fontSize=13, textColor=WHITE,
            alignment=TA_CENTER, leading=16)),
    ]]
    badge_table = Table(badge_data, colWidths=[80*mm])
    badge_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), badge_color),
        ('ROWBACKGROUNDS', (0,0), (-1,-1), [badge_color]),
        ('TOPPADDING', (0,0), (-1,-1), 8),
        ('BOTTOMPADDING', (0,0), (-1,-1), 8),
        ('ALIGN', (0,0), (-1,-1), 'CENTER'),
    ]))

    # Cover info table
    cover_rows = [
        [Paragraph('<b>Project Name</b>', S['label']),   Paragraph(project.get('name','—'), S['bold'])],
        [Paragraph('<b>Project Developer</b>', S['label']), Paragraph(project.get('project_developer') or '—', S['body'])],
        [Paragraph('<b>Location</b>', S['label']),        Paragraph(project.get('location') or '—', S['body'])],
        [Paragraph('<b>Registry</b>', S['label']),         Paragraph(registry_slug, S['body'])],
        [Paragraph('<b>Methodology</b>', S['label']),      Paragraph(methodology, S['body'])],
        [Paragraph('<b>Vintage Year</b>', S['label']),     Paragraph(str(project.get('vintage_year') or '—'), S['body'])],
        [Paragraph('<b>Report Date</b>', S['label']),      Paragraph(gen_str, S['body'])],
        [Paragraph('<b>Report Type</b>', S['label']),      Paragraph('Third-Party Verification Report', S['body'])],
    ]
    cover_table = Table(cover_rows, colWidths=[45*mm, 110*mm])
    cover_table.setStyle(TableStyle([
        ('VALIGN', (0,0), (-1,-1), 'TOP'),
        ('TOPPADDING', (0,0), (-1,-1), 4),
        ('BOTTOMPADDING', (0,0), (-1,-1), 4),
        ('LINEBELOW', (0,0), (-1,-2), 0.3, BORDER),
    ]))

    # Layout cover as two-column
    cover_layout = Table(
        [[badge_table, cover_table]],
        colWidths=[88*mm, 82*mm],
        rowHeights=[None]
    )
    cover_layout.setStyle(TableStyle([
        ('VALIGN', (0,0), (-1,-1), 'TOP'),
        ('LEFTPADDING', (1,0), (1,0), 14),
        ('TOPPADDING', (0,0), (-1,-1), 0),
        ('BOTTOMPADDING', (0,0), (-1,-1), 0),
    ]))

    story.append(Paragraph('Verification Report', S['title']))
    story.append(Paragraph('DataSentinel V&amp;V Platform  ·  Third-Party Carbon Registry Verification', S['subtitle']))
    story.append(Spacer(1, 6*mm))
    story.append(cover_layout)
    story.append(Spacer(1, 6*mm))
    story.append(HRFlowable(width='100%', thickness=1, color=BORDER))
    story.append(Spacer(1, 4*mm))

    # ── EXECUTIVE SUMMARY ───────────────────────────────────────────────────
    story.append(Paragraph('Executive Summary', S['h1']))
    summary = report.get('summary', '')
    story.append(Paragraph(summary, S['body']))
    story.append(Spacer(1, 3*mm))

    # Stats row
    p = stats.get('passed', 0)
    f = stats.get('failed', 0)
    w = stats.get('warnings', 0)
    t = stats.get('checkpoints_total', p+f+w)
    credit = report.get('credit_estimate')
    credit_unit = report.get('credit_unit') or 'tCO2e'

    stat_data = [[
        Paragraph(f'<b><font size="18">{t}</font></b><br/><font size="7" color="#8A8480">TOTAL CHECKPOINTS</font>', ParagraphStyle('sc',alignment=TA_CENTER,leading=20)),
        Paragraph(f'<b><font size="18" color="#7A8C2E">{p}</font></b><br/><font size="7" color="#8A8480">PASSED</font>', ParagraphStyle('sc2',alignment=TA_CENTER,leading=20)),
        Paragraph(f'<b><font size="18" color="#C9A227">{w}</font></b><br/><font size="7" color="#8A8480">WARNINGS</font>', ParagraphStyle('sc3',alignment=TA_CENTER,leading=20)),
        Paragraph(f'<b><font size="18" color="#C0392B">{f}</font></b><br/><font size="7" color="#8A8480">FAILED</font>', ParagraphStyle('sc4',alignment=TA_CENTER,leading=20)),
        Paragraph(f'<b><font size="14">{f"{credit:,.0f}" if credit else "N/A"}</font></b><br/><font size="7" color="#8A8480">EST. {credit_unit}</font>', ParagraphStyle('sc5',alignment=TA_CENTER,leading=18)),
    ]]
    stat_table = Table(stat_data, colWidths=[34*mm]*5)
    stat_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), SURFACE),
        ('BOX', (0,0), (-1,-1), 0.5, BORDER),
        ('INNERGRID', (0,0), (-1,-1), 0.3, BORDER),
        ('ALIGN', (0,0), (-1,-1), 'CENTER'),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ('TOPPADDING', (0,0), (-1,-1), 8),
        ('BOTTOMPADDING', (0,0), (-1,-1), 8),
    ]))
    story.append(stat_table)
    story.append(Spacer(1, 5*mm))

    # Outcome explanation
    outcome_explanations = {
        'verified': 'All critical checkpoints have been reviewed and passed. The project meets the registry requirements and is recommended for certificate issuance. The indicative credit estimate provided in this report may be used as the basis for credit award.',
        'conditional': 'All critical checkpoints passed, however certain items require clarification or supplementary documentation before final certificate issuance. A Conditions List is appended to this report. The project developer must resolve all conditions and resubmit for final verification.',
        'not_verified': 'One or more critical checkpoints have failed verification. The project does not meet the registry requirements for certificate issuance. The project developer must address all failed checkpoints and resubmit a complete documentation package for a new verification round.',
    }
    box_color = outcome_color
    explanation = outcome_explanations.get(outcome, '')
    exp_table = Table([[Paragraph(f'<b>{outcome_label}:</b> {explanation}', ParagraphStyle('exp', fontName='Helvetica', fontSize=9, textColor=WHITE, leading=13, alignment=TA_JUSTIFY))]],
                      colWidths=[170*mm])
    exp_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), box_color),
        ('TOPPADDING', (0,0), (-1,-1), 10),
        ('BOTTOMPADDING', (0,0), (-1,-1), 10),
        ('LEFTPADDING', (0,0), (-1,-1), 12),
        ('RIGHTPADDING', (0,0), (-1,-1), 12),
    ]))
    story.append(exp_table)

    # Conditions
    conditions = report.get('conditions', [])
    if conditions:
        story.append(Spacer(1, 5*mm))
        story.append(Paragraph('Conditions for Certification', S['h1']))
        story.append(Paragraph('The following conditions must be resolved before final certificate issuance:', S['body']))
        for i, cond in enumerate(conditions, 1):
            cp_id = cond.get('checkpoint', '')
            note = cond.get('note', '')
            story.append(Paragraph(f'{i}. <b>[{cp_id}]</b> {note}', S['body']))

    # Recommendations
    recs = report.get('recommendations', [])
    if recs:
        story.append(Spacer(1, 4*mm))
        story.append(Paragraph('Recommendations', S['h1']))
        for rec in recs:
            story.append(Paragraph(f'• {rec}', S['body']))

    story.append(PageBreak())

    # ── CHECKPOINT FINDINGS ─────────────────────────────────────────────────
    story.append(Paragraph('Checkpoint Findings', S['h1']))
    story.append(Paragraph(
        'The following table presents the verification findings for each checkpoint, '
        'including the AI analysis result, verifier decision, and supporting evidence.',
        S['body']))
    story.append(Spacer(1, 3*mm))

    # Group checkpoints by category
    from collections import OrderedDict
    cats: Dict[str, List] = OrderedDict()
    for cp in checkpoints:
        cat = cp.get('category', 'Other')
        cats.setdefault(cat, []).append(cp)

    for cat, cps in cats.items():
        story.append(KeepTogether([
            Spacer(1, 2*mm),
            Paragraph(cat.upper(), S['h2']),
        ]))

        for cp in cps:
            cp_id   = cp.get('checkpoint_id', '')
            name    = cp.get('name', '')
            req     = cp.get('requirement', '')
            finding = cp.get('ai_finding') or ''
            v_status= cp.get('verifier_status') or cp.get('status', 'pending')
            v_note  = cp.get('verifier_note') or ''
            conf    = cp.get('ai_confidence')
            eff_status = v_status if v_status else cp.get('status','pending')
            sc = _status_color(eff_status)
            status_label = eff_status.upper()

            # Status badge cell
            status_cell = Table([[Paragraph(f'<font color="white"><b>{status_label}</b></font>',
                ParagraphStyle('sb', fontName='Helvetica-Bold', fontSize=7, textColor=WHITE, alignment=TA_CENTER))]],
                colWidths=[22*mm])
            status_cell.setStyle(TableStyle([
                ('BACKGROUND', (0,0), (-1,-1), sc),
                ('TOPPADDING', (0,0), (-1,-1), 3),
                ('BOTTOMPADDING', (0,0), (-1,-1), 3),
                ('ALIGN', (0,0), (-1,-1), 'CENTER'),
            ]))

            # Checkpoint header row
            hdr_data = [[
                Paragraph(cp_id, S['cp_id']),
                Paragraph(f'<b>{name}</b>', ParagraphStyle('cpn', fontName='Helvetica-Bold', fontSize=9, textColor=DARK, leading=11)),
                status_cell,
            ]]
            hdr_table = Table(hdr_data, colWidths=[24*mm, 118*mm, 28*mm])
            hdr_table.setStyle(TableStyle([
                ('BACKGROUND', (0,0), (-1,-1), SURFACE2),
                ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
                ('TOPPADDING', (0,0), (-1,-1), 5),
                ('BOTTOMPADDING', (0,0), (-1,-1), 5),
                ('LEFTPADDING', (0,0), (0,0), 6),
                ('RIGHTPADDING', (0,0), (-1,-1), 6),
                ('LINEBELOW', (0,0), (-1,-1), 0.3, BORDER),
            ]))

            # Detail rows
            detail_rows = []
            detail_rows.append([
                Paragraph('Requirement', S['label']),
                Paragraph(req[:300] + ('…' if len(req)>300 else ''), S['body_sm']),
            ])
            if finding:
                detail_rows.append([
                    Paragraph('AI Finding', S['label']),
                    Paragraph(finding[:400] + ('…' if len(finding)>400 else ''), S['finding_ok']),
                ])
            if conf is not None:
                detail_rows.append([
                    Paragraph('AI Confidence', S['label']),
                    Paragraph(f'{int(conf*100)}%', S['body_sm']),
                ])
            if v_note:
                detail_rows.append([
                    Paragraph('Verifier Note', S['label']),
                    Paragraph(f'<b>{v_note[:400]}</b>', ParagraphStyle('vn', fontName='Helvetica-Bold', fontSize=8, textColor=DARK, leading=11)),
                ])

            det_table = Table(detail_rows, colWidths=[24*mm, 146*mm])
            det_table.setStyle(TableStyle([
                ('BACKGROUND', (0,0), (-1,-1), WHITE),
                ('VALIGN', (0,0), (-1,-1), 'TOP'),
                ('TOPPADDING', (0,0), (-1,-1), 3),
                ('BOTTOMPADDING', (0,0), (-1,-1), 3),
                ('LEFTPADDING', (0,0), (0,-1), 6),
                ('LINEBELOW', (0,-1), (-1,-1), 0.5, BORDER),
            ]))

            story.append(KeepTogether([hdr_table, det_table, Spacer(1, 1.5*mm)]))

    # ── DOCUMENT INVENTORY ───────────────────────────────────────────────────
    story.append(PageBreak())
    story.append(Paragraph('Document Inventory', S['h1']))
    story.append(Paragraph('The following documents were submitted as part of this verification package:', S['body']))
    story.append(Spacer(1, 3*mm))

    doc_hdr = [[ Paragraph('Document Name', S['label']), Paragraph('Type', S['label']),
                 Paragraph('Status', S['label']), Paragraph('Size', S['label']) ]]
    doc_rows = []
    for d in documents:
        name_str = (d.get('name') or '—')[:55]
        dtype = (d.get('document_type') or '—').replace('_',' ').title()[:30]
        dstatus = (d.get('status') or '—').title()
        fsize = d.get('file_size') or 0
        size_str = f'{fsize//1024}KB' if fsize > 1024 else (f'{fsize}B' if fsize else '—')
        doc_rows.append([
            Paragraph(name_str, S['body_sm']),
            Paragraph(dtype, S['body_sm']),
            Paragraph(dstatus, S['body_sm']),
            Paragraph(size_str, S['body_sm']),
        ])

    if doc_rows:
        all_doc_rows = doc_hdr + doc_rows
        doc_table = Table(all_doc_rows, colWidths=[85*mm, 45*mm, 22*mm, 18*mm])
        doc_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), SURFACE2),
            ('ROWBACKGROUNDS', (0,1), (-1,-1), [WHITE, SURFACE]),
            ('BOX', (0,0), (-1,-1), 0.5, BORDER),
            ('INNERGRID', (0,0), (-1,-1), 0.3, BORDER),
            ('TOPPADDING', (0,0), (-1,-1), 4),
            ('BOTTOMPADDING', (0,0), (-1,-1), 4),
            ('LEFTPADDING', (0,0), (-1,-1), 6),
            ('VALIGN', (0,0), (-1,-1), 'TOP'),
        ]))
        story.append(doc_table)

    # ── SIGNATURE / DECLARATION ──────────────────────────────────────────────
    story.append(Spacer(1, 8*mm))
    story.append(HRFlowable(width='100%', thickness=0.5, color=BORDER))
    story.append(Spacer(1, 4*mm))
    story.append(Paragraph('Verification Declaration', S['h1']))
    story.append(Paragraph(
        'This report has been generated by the DataSentinel V&amp;V Platform on behalf of the assigned verifier. '
        'The findings contained herein are based on the documents submitted by the project developer and the '
        'automated analysis performed by the DataSentinel AI verification engine, supplemented by manual '
        'verifier review. This report does not constitute legal advice and the issuing registry retains '
        'final authority over certificate issuance decisions.',
        S['body']))
    story.append(Spacer(1, 8*mm))

    # Signature boxes
    sig_data = [[
        Paragraph('Lead Verifier', S['label']),
        Paragraph('Date', S['label']),
        Paragraph('Registry Reference', S['label']),
    ],[
        Paragraph(' ', S['body']),
        Paragraph(gen_str, S['body_sm']),
        Paragraph(' ', S['body']),
    ]]
    sig_table = Table(sig_data, colWidths=[70*mm, 50*mm, 50*mm])
    sig_table.setStyle(TableStyle([
        ('LINEBELOW', (0,1), (-1,1), 0.8, DARK),
        ('TOPPADDING', (0,0), (-1,-1), 3),
        ('BOTTOMPADDING', (0,0), (-1,-1), 14),
        ('LEFTPADDING', (0,0), (-1,-1), 0),
    ]))
    story.append(sig_table)

    story.append(Spacer(1, 4*mm))
    story.append(Paragraph(
        f'Report ID: VV-{project.get("id","")[:8].upper()}  ·  Generated: {gen_str}  ·  DataSentinel V&amp;V Platform v3.2',
        ParagraphStyle('footer_note', fontName='Helvetica', fontSize=7, textColor=MUTED, alignment=TA_CENTER)))

    # Build
    doc.build(story, onFirstPage=_header_footer, onLaterPages=_header_footer)
    return buf.getvalue()
