import type { Project, ProjectStatus, Registry } from "./types";

export const PROJECTS: Project[] = [
  {
    id: "kasigau",
    tenantId: "verdant",
    name: "Kasigau Corridor REDD+",
    country: "Kenya",
    region: "Taita Taveta",
    lat: -3.83,
    lng: 38.65,
    status: "issued",
    registry: "Verra VCS",
    methodology: "VM0009 v4.0",
    methodologyKey: "vm0009",
    afolu: true,
    developer: "Wildlife Works",
    hectares: 200_000,
    creditsIssued: 1_420_000,
    annualForecast: 310_000,
    vintage: 2025,
    sensors: 34,
    lastSyncMinutes: 12,
    bufferPct: 18,
    creditingStart: 2021,
    creditingYears: 30,
  },
  {
    id: "rimba-raya",
    tenantId: "verdant",
    name: "Rimba Raya Peatland Reserve",
    country: "Indonesia",
    region: "Central Kalimantan",
    lat: -2.94,
    lng: 112.51,
    status: "verification",
    registry: "Verra VCS",
    methodology: "VM0007 v1.6",
    methodologyKey: "vm0007",
    afolu: true,
    developer: "InfiniteEARTH",
    hectares: 64_000,
    creditsIssued: 890_000,
    annualForecast: 240_000,
    vintage: 2025,
    sensors: 52,
    lastSyncMinutes: 4,
    bufferPct: 22,
    creditingStart: 2022,
    creditingYears: 30,
  },
  {
    id: "sahel-agro",
    tenantId: "verdant",
    name: "Sahel Agroforestry Cluster",
    country: "Niger",
    region: "Maradi",
    lat: 13.51,
    lng: 7.11,
    status: "monitoring",
    registry: "Gold Standard",
    methodology: "AR-AMS0007 v3.0",
    methodologyKey: "ar-ams0007",
    afolu: true,
    developer: "Sahel Regreening Trust",
    hectares: 19_200,
    creditsIssued: 31_000,
    annualForecast: 46_000,
    vintage: 2026,
    sensors: 74,
    lastSyncMinutes: 19,
    bufferPct: 17,
    creditingStart: 2023,
    creditingYears: 20,
  },
  {
    id: "amazon-arr",
    tenantId: "verdant",
    name: "Amazon Basin ARR Mosaic",
    country: "Peru",
    region: "Ucayali",
    lat: -8.42,
    lng: -74.53,
    status: "draft",
    registry: "Verra VCS",
    methodology: "VM0047 v1.1",
    methodologyKey: "vm0047",
    afolu: true,
    developer: "Selva Viva Alianza",
    hectares: 28_400,
    creditsIssued: 0,
    annualForecast: 88_000,
    vintage: 2028,
    sensors: 22,
    lastSyncMinutes: 96,
    bufferPct: 25,
    creditingStart: 2026,
    creditingYears: 40,
  },
  {
    id: "cerrado-soil",
    tenantId: "helios",
    name: "Cerrado Regenerative Soil Carbon",
    country: "Brazil",
    region: "Goiás",
    lat: -15.62,
    lng: -47.91,
    status: "monitoring",
    registry: "Verra VCS",
    methodology: "VM0042 v2.1",
    methodologyKey: "vm0042",
    afolu: true,
    developer: "Solo Vivo Agro",
    hectares: 41_500,
    creditsIssued: 96_000,
    annualForecast: 128_000,
    vintage: 2026,
    sensors: 148,
    lastSyncMinutes: 2,
    bufferPct: 15,
    creditingStart: 2023,
    creditingYears: 20,
  },
  {
    id: "great-plains",
    tenantId: "helios",
    name: "Great Plains Grassland Sequestration",
    country: "United States",
    region: "South Dakota",
    lat: 44.47,
    lng: -100.42,
    status: "monitoring",
    registry: "Verra VCS",
    methodology: "VM0032 v1.1",
    methodologyKey: "vm0032",
    afolu: true,
    developer: "Prairie Carbon Co-op",
    hectares: 87_300,
    creditsIssued: 54_000,
    annualForecast: 92_000,
    vintage: 2026,
    sensors: 96,
    lastSyncMinutes: 7,
    bufferPct: 12,
    creditingStart: 2024,
    creditingYears: 20,
  },
  {
    id: "loess-plateau",
    tenantId: "helios",
    name: "Loess Plateau Afforestation",
    country: "China",
    region: "Shaanxi",
    lat: 36.51,
    lng: 109.49,
    status: "validation",
    registry: "Gold Standard",
    methodology: "AR-ACM0003 v2.0",
    methodologyKey: "ar-acm0003",
    afolu: true,
    developer: "Yellow River Forestry",
    hectares: 33_800,
    creditsIssued: 0,
    annualForecast: 74_000,
    vintage: 2027,
    sensors: 61,
    lastSyncMinutes: 38,
    bufferPct: 20,
    creditingStart: 2025,
    creditingYears: 30,
  },
  {
    id: "nordic-biochar",
    tenantId: "terrafix",
    name: "Nordic Biochar Facility",
    country: "Finland",
    region: "Uusimaa",
    lat: 60.21,
    lng: 24.94,
    status: "issued",
    registry: "Puro.earth",
    methodology: "Puro Biochar Edition 2025",
    methodologyKey: "puro-biochar",
    afolu: false,
    developer: "Boreal Carbon Works",
    hectares: 6,
    creditsIssued: 118_000,
    annualForecast: 64_000,
    vintage: 2026,
    sensors: 28,
    lastSyncMinutes: 1,
    bufferPct: 5,
    creditingStart: 2022,
    creditingYears: 10,
  },
  {
    id: "north-sea-dac",
    tenantId: "terrafix",
    name: "North Sea DAC + Storage",
    country: "Norway",
    region: "Rogaland",
    lat: 58.97,
    lng: 5.73,
    status: "validation",
    registry: "Isometric",
    methodology: "Isometric DAC v1.3",
    methodologyKey: "isometric-dac",
    afolu: false,
    developer: "Vestland Carbon AS",
    hectares: 12,
    creditsIssued: 0,
    annualForecast: 51_000,
    vintage: 2027,
    sensors: 210,
    lastSyncMinutes: 1,
    bufferPct: 3,
    creditingStart: 2025,
    creditingYears: 15,
  },
  {
    id: "rajasthan-stoves",
    tenantId: "terrafix",
    name: "Rajasthan Improved Cookstoves",
    country: "India",
    region: "Jaipur",
    lat: 26.91,
    lng: 75.79,
    status: "verification",
    registry: "Gold Standard",
    methodology: "TPDDTEC v4.0",
    methodologyKey: "tpddtec",
    afolu: false,
    developer: "Aravalli Clean Energy",
    hectares: 0,
    creditsIssued: 402_000,
    annualForecast: 143_000,
    vintage: 2025,
    sensors: 1_240,
    lastSyncMinutes: 6,
    bufferPct: 0,
    creditingStart: 2021,
    creditingYears: 10,
  },
  {
    id: "fujairah-mineral",
    tenantId: "fourfourone",
    name: "Fujairah Peridotite Mineralisation",
    country: "United Arab Emirates",
    region: "Fujairah",
    lat: 25.29,
    lng: 56.26,
    status: "monitoring",
    registry: "Isometric",
    methodology: "Isometric In-Situ Mineralization v1.0",
    methodologyKey: "isometric-insitu-mineralization",
    afolu: false,
    developer: "44.01",
    hectares: 9,
    creditsIssued: 6_400,
    annualForecast: 24_000,
    vintage: 2026,
    sensors: 186,
    lastSyncMinutes: 1,
    bufferPct: 2,
    creditingStart: 2025,
    creditingYears: 15,
  },
];

export const REGISTRIES: Registry[] = [
  "Verra VCS",
  "Gold Standard",
  "Puro.earth",
  "Isometric",
];

export const STATUS_META: Record<
  ProjectStatus,
  { label: string; color: string }
> = {
  draft: { label: "Draft", color: "#7b8aa5" },
  validation: { label: "Validation", color: "#f5b544" },
  monitoring: { label: "Monitoring", color: "#4cc4ff" },
  verification: { label: "Verification", color: "#9b8cff" },
  issued: { label: "Issued", color: "#34e0a1" },
};

export function getProject(id: string | null): Project | undefined {
  if (!id) return undefined;
  return PROJECTS.find((project) => project.id === id);
}
